name: openui-app
services:
  - name: web
    source_dir: /
    github:
      repo: daveee08/openui-with-openrouter
      branch: main
    run_command: cd backend && python -m open_webui.main
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
    envs:
      - key: PYTHONPATH
        value: "/app/backend"
      - key: DATA_DIR
        value: "/app/backend/data"
      - key: UPLOAD_DIR
        value: "/app/backend/data/uploads"
      - key: CACHE_DIR
        value: "/app/backend/data/cache"
      - key: ENABLE_SIGNUP
        value: "True"
      - key: WEBUI_SECRET_KEY
        value: "your-secret-key-here"
        type: SECRET
      - key: STORAGE_PROVIDER
        value: "s3"
      - key: S3_BUCKET_NAME
        value: "your-s3-bucket-name"
        type: SECRET
      - key: S3_ACCESS_KEY_ID
        value: "your-s3-access-key"
        type: SECRET
      - key: S3_SECRET_ACCESS_KEY
        value: "your-s3-secret-key"
        type: SECRET
      - key: S3_REGION_NAME
        value: "us-east-1"
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
      - key: CORS_ALLOW_ORIGIN
        value: "https://your-app-name.ondigitalocean.app"

  - name: frontend
    source_dir: /
    github:
      repo: daveee08/openui-with-openrouter
      branch: main
    build_command: npm install && npm run build
    run_command: npx serve build -s -l 3000
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: VITE_API_BASE_URL
        value: "https://your-app-name-web.ondigitalocean.app"

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
